// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzcpzoiezcyrlrscrnxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y3B6b2llemN5cmxyc2NybnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjgzNzUsImV4cCI6MjA1OTE0NDM3NX0.KyRnHMRlpHwgJRcWLMCQNSVeSnygfe_LpgwB730af7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);